AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # according to VGG-16
BATCH_SIZE: 16 #as local training would be done
INCLUDE_TOP: False #to exclude the FC layers and keep the CONV Block
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
